version: '3.7'
services:
  emcc:
    container_name: image-optimization
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /app
      - /emsdk/upstream/emscripten/cache
      - ../Makefile:/app/Makefile
      - ../src:/app/src
      - ../dist:/app/dist
volumes:
  app:
  cache:
