name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
      - name: Test | Build test
        run: pnpm build
      - name: Post | Save Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4.5.0
        with:
          name: build
          path: ./packages/wasm/dist
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
      - name: Setup | Restore Build Artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: build
          path: ./packages/wasm/dist
      - name: Test | Lint test
        run: pnpm lint
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
      - name: Setup | Restore Build Artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: build
          path: ./packages/wasm/dist
      - name: Test | Integration test
        run: pnpm test
